[tools]
awscli = "latest"
aws-vault = "latest"
azure = "latest"
azure-kubelogin = "latest"
cosign = "latest"
flux2 = "latest"
gcloud = "latest"
gemini-cli = "latest"
go = "latest"
golangci-lint = "latest"
hadolint = "latest"
helm = "latest"
hugo-extended = "latest"
k3d = "latest"
k3s = "latest"
k3sup = "latest"
k9s = "latest"
krew = "latest"
kubectl = "latest"
kubectx = "latest"
kubens = "latest"
kustomize = "latest"
node = "latest"
terraform = "latest"
trivy = "latest"
uv = "latest"
watchexec = "latest"
yq = "latest"
